complexity:
  # Compose functions tend to be longer and have a lot of parameters
  LongMethod:
    threshold: 100
  LongParameterList:
    ignoreDefaultParameters: true

naming:
  # Compose functions are uppercase
  FunctionNaming:
    functionPattern: "[a-zA-Z0-9]*"
  # Ofter files with Composable function start with accessory interfaces
  MatchingDeclarationName:
    active: false

style:
  # Library is still in alpha, let's allow TODOs
  ForbiddenComment:
    comments: [ ]
  WildcardImport:
    excludeImports:
      - io.github.compose4gtk.adw.components.*
      - io.github.compose4gtk.gtk.components.*

formatting:
  NoWildcardImports:
    packagesToUseImportOnDemandProperty:
      "io.github.compose4gtk.adw.components.*,io.github.compose4gtk.gtk.components.*"
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
  Filename:
    # Examples have a number prepended to the file name, to ensure users can read them in order
    excludes: '**/examples/**'

Compose:
  active: true
  ModifierMissing:
    excludes: '**/test/**'
  MutableStateParam:
    excludes: '**/test/**'
  CompositionLocalAllowlist:
    active: true
    allowedCompositionLocals:
      - LocalApplication
      - LocalApplicationWindow